name: CLI Test
on:
  pull_request:
    branches:
      - canary
      - "*.x"
      - 'main'
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  cli-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build CLI
        run: pnpm run build

      - name: Test CLI against this PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1)
          REPO=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          
          node dist/cli.js \
            "$OWNER" \
            "$REPO" \
            "${{ github.event.pull_request.base.sha }}" \
            "${{ github.event.pull_request.head.sha }}" \
            --output json \
            --comment-summary-in-pr always \
            --pr-number "${{ github.event.pull_request.number }}"
